version: '3'
services:
  express-app:
    build: 
      context: .
      target: development
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE-ENV=Development
    command: npm run start:dev 
  
